my_blog/urls.py
from django.urls import path
from . import views

app_name = 'my_blog'

urlpatterns = [

    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),




]

personal_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

app_name = 'portfolio'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('my_blog/', include('my_blog.urls')),
    path('pic/', views.pic, name='pic'),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

my_blog/models.py
from django.db import models

class Blogs(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100) # Title discription or Text, Header
    description = models.CharField(max_length=250) # Body text, the text below header
    image = models.ImageField(upload_to='portfolio/images/') # we store our images in portfolio/images/ just like templates
    url = models.URLField(blank=True) # we put blank because we want some of our pages to be clickable and some not. Blank is optional

    def __str__(self):
        return self.title

my_blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blogs

def all_blogs(request):
    blog = Blogs.objects.all()
    return render(request, 'my_blog/all_blogs.html', {'blogs':blog})

def detail(request, blog_id):
    blog = get_object_or_404(Blogs, pk=blog_id)

    return render(request, 'my_blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

def pic(request):
    return render(request, 'portfolio/pic.html')

# Create your views here.

my_blog/templates/my_blog/all_blogs.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<div class="p-3 mb-2 bg-dark text-white">
<div class='container text-center'>

<h2 class='alert alert-success'> I have written {{ blogs.count }} blog{{ blogs.count|pluralize }} </h2>

{% for num in blogs %}
<a href="{% url 'my_blog:detail' num.id %}"<h1 class="text-info"> Blogs </h1>
  <p> {{ num.description|truncatechars:20 }}


<h2 class="text-danger">{{ num.title }}</h2>


{{ num.date }}
<br>
<br>



{% endfor %}
</div>
</div>

my_blog/templates/my_blog/detail.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<h1 class='text-warning'>{{ blog.title }}</h1>
<h2 class = "alert alert-success">{{ blog.description }}</h2>
<br>
<br>
<button type="button" class="btn btn-info"> <a href="{% url 'home'  %}"> home page </a> </button>

portfolio/templates/portfolio/base.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<div class="p-3 mb-2 bg-danger text-white">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}"><h1 class="alert alert-info" >Navbar</h1></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}"><p  class="alert alert-danger" >Home </p></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pic' %}"><p class="alert alert-info" >About</p></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><p  class="alert alert-success" >
            Blogs Bar
          </p></a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'my_blog:all_blogs' %}">Blogs</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><p  class="alert alert-warning" >Disabled</p></a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}{% endblock %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>
</div>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<div class="p-3 mb-2 bg-dark text-white">
    <div class='container text-center'>
    <a class="text-warning" href="{% url 'pic' %}"> Steps to learn Django </a>




    {% for project in  projects %}

    <h2 class="text-success">{{ project.title }}</h2>

    <p class="text-danger">{{ project.description }}</p>



    <img src="{{ project.image.url }}" height = 400 width=600>
    <br>
    <br>

    {% if project.url %}

    <a href="{{ product.url }}" class="btn btn-primary"> Link to image </a>






    {% endif %}
    {% endfor %}

    <a href="{% url 'my_blog:all_blogs' %}"> Blogs </a>


    </div>
    </div>



  {% endblock %}

portfolio/templates/portfolio/pic.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<div class="p-3 mb-2 bg-danger text-white">
{% extends 'portfolio/base.html' %}

{% block content %}

<h1 class='text-info'> PYTHONS </h1>
<br>
<a href="{% url 'home' %}"> Pythons </a>
<br>

{% load static %}

<h2 class='text-info'> Green </h2>

<img src="{% static 'portfolio/learn-python-tutorials.jpg' %}">

<br>
<br>
<h2 class='text-info'> Yellow </h2>
<img src="{% static 'portfolio/1200px-burmese_python_02-100637340-large.jpg' %}">

<br>
<h2> Greenish </h2>

<img src="{% static 'portfolio/shutterstock_1386882278-1.jpg' %}">

<a href="{% static 'portfolio/Random_password_gen.docx' %}"> Word Document </a>

{% endblock %}

</div>